services:

  mongo:
    image: mongo:8
    container_name: mongo

    command:
      - mongod
      - --replSet
      - rs0
      - --bind_ip_all

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  app:
    build: .

    container_name: inventory-api

    ports:
      - "3000:3000"

    depends_on:
      - mongo

volumes:
  - mongo_data:/data/db
  - ./docker/mongo/init-replica.js:/docker-entrypoint-initdb.d/init-replica.js