services:
  mongo:
    image: mongo:8
    container_name: mongo
    hostname: mongo
    command:
      - mongod
      - --replSet
      - rs0
      - --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
      - mongo_data:/data/db

volumes:
  mongo_data: